[build]
  base = ""
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin"

[[headers]]
  for = "/modelo_navio/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/modelo_rebocador/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
